// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB369wHIDNiyQS3RfxwoP4fBzeYEStYHK8',
    appId: '1:17530217893:web:4ce48cb97e66b6e311344c',
    messagingSenderId: '17530217893',
    projectId: 'edubridge-3fd5d',
    authDomain: 'edubridge-3fd5d.firebaseapp.com',
    storageBucket: 'edubridge-3fd5d.appspot.com',
    measurementId: 'G-GKLBL32GM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6VNNlHxXhBbb3V11ojTYgl4mB4bchzY',
    appId: '1:17530217893:android:c69ed405460a7aff11344c',
    messagingSenderId: '17530217893',
    projectId: 'edubridge-3fd5d',
    storageBucket: 'edubridge-3fd5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmU_1d4_tSHMDpmSbhlr3Tqq1FWggRDRM',
    appId: '1:17530217893:ios:6cd11685213a248611344c',
    messagingSenderId: '17530217893',
    projectId: 'edubridge-3fd5d',
    storageBucket: 'edubridge-3fd5d.appspot.com',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmU_1d4_tSHMDpmSbhlr3Tqq1FWggRDRM',
    appId: '1:17530217893:ios:6cd11685213a248611344c',
    messagingSenderId: '17530217893',
    projectId: 'edubridge-3fd5d',
    storageBucket: 'edubridge-3fd5d.appspot.com',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB369wHIDNiyQS3RfxwoP4fBzeYEStYHK8',
    appId: '1:17530217893:web:78fb920e15e0641911344c',
    messagingSenderId: '17530217893',
    projectId: 'edubridge-3fd5d',
    authDomain: 'edubridge-3fd5d.firebaseapp.com',
    storageBucket: 'edubridge-3fd5d.appspot.com',
    measurementId: 'G-7TY1WC3VQ9',
  );
}
